# Generated by Django 5.0.3 on 2024-03-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='Email_address',
            field=models.CharField(default='email'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='Password',
            field=models.CharField(default='password'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_id',
            field=models.IntegerField(default='3'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(default='vjd'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='john', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_name',
            field=models.CharField(default='name', max_length=40),
        ),
    ]
