# Generated by Django 5.0.3 on 2024-03-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_restaurant_email_address_restaurant_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='jambu', max_length=50)),
                ('From_address', models.TextField(max_length=100)),
                ('To_address', models.TextField(max_length=100)),
                ('Ordered_restaurant', models.CharField(max_length=30)),
                ('Ordered_food', models.CharField(max_length=40)),
            ],
        ),
    ]
